spring.application.name=api
spring.datasource.url=jdbc:mysql://localhost:3306/vollmed_api
spring.datasource.username=root
<<<<<<< HEAD
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
=======
spring.datasource.password=(***)
>>>>>>> 0d6808662b7a6969450526369cc20f135a178fa0
